### ISSUE TITLE
Detailed failure generation rules

### ISSUE THREAD

**Issue by dmdashenkov** [SpineEventEngine/documentation#3]
Now, to understand how do we write proto definitions for business failures, I had to investigate codebase of `tools` repository (Gradle plugin for instance). 
Since there are a few key differences in writing usual definitions and failures (e.g. `java_outer_classname` option specification etc.), it would be nice if there was a detailed description of those differences.

**Comment by alexander-yevsyukov** [comment]
Transformed to
https://github.com/SpineEventEngine/SpineEventEngine.github.io/issues/130
